### ISSUE TITLE
Act believes that the payment type is YEF instead of NONE

### ISSUE THREAD

**Issue by alexm** [Act-Conferences/barcelona2015#2]
Template `user/main` checks if `global.config.payment_type != "NONE"` before showing a message to users saying this:

> You have not confirmed your participation to this conference yet. Please consider doing so once our online payment system is ready.

But the `act.ini` says that payment type is `NONE` so what's going on here?

**Comment by maddingue** [comment]
There's an override in the global Act config, where we, the Act admins, copy the payment type. This is in order to prevent organizers from using a payment system before being sure that the people managing said system knows about it. For barcelona2015, payment_type is set to YEF there.

**Comment by alexm** [comment]
@maddingue we're not using YEF this time, so could you please set that override to NONE?

**Comment by maddingue** [comment]
Done.

**Comment by alexm** [comment]
Thanks a lot!
